project:
  type: book
  output-dir: docs

book:
  title: "Difference-in-Differences (DiD) Resources"
  subtitle: "Resources for Causal Panel Analysis"
  author: "Kevin Lingfeng Li (London School of Economics)"
  search: false
  chapters:
    - text: "Welcome!"
      href: index.qmd
    - text: "---"
    - panelview.qmd
    - twfe.qmd
    - bacon.qmd
    - sunab.qmd
    - csdid.qmd
    - fect.qmd
    - didmultiple.qmd
    - panelmatch.qmd
    - did2s.qmd
    - impute.qmd
    - etwfe.qmd
    - text: "---"
    - fixest.qmd
    


format:
  html:
    theme: default
    fontsize: 11.5pt
    css: styles.css
    highlight-style: arrow
    grid:
      sidebar-width: 220px
      body-width: 850px
      margin-width: 210px
    number-depth: 1
    html-math-method: mathjax
    crossref:
      eq-prefix: eq.
      def-prefix: definition
      thm-prefix: theorem
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
    include-after-body:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">


editor: visual

