#### Welcome! {.unnumbered}

This repository is a collection of resources on Difference-in-Differences (DiD) packages in **R** and **Python** (and Julia coming soon). For a more in-depth overview of the DiD design and estimators, see this pdf.

+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| Estimator                             | Brief Description                                                                                                                                                                                     | R                                                                     | Python                     |
+=======================================+=======================================================================================================================================================================================================+=======================================================================+============================+
| two-way fixed effects (twfe)          | ::: small                                                                                                                                                                                             | [`fixest`](fixest.qmd) [`bacondecomp`](bacon.qmd)                     | [`pyfixest`](pyfixest.qmd) |
|                                       | Standard estimator for DiD. Can be biased with staggered treatment or non-absorbing treatment.                                                                                                        |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| interaction-weighted (iw)             | ::: small                                                                                                                                                                                             | [`fixest`](fixest.qmd)                                                | --                         |
|                                       | Sun and Abraham (2020). Matching and reweighting regression estimator for staggered treatment.                                                                                                        |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| doubly-robust (dr)                    | ::: small                                                                                                                                                                                             | [`did`](did.qmd)                                                      | [`csdid`](csdid.qmd)       |
|                                       | Callaway and Sant'Anna (2021). Matching and reweighting semi-parametric estimator for staggered treatment.                                                                                            |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| inverse probability weighting (ipw)   | ::: small                                                                                                                                                                                             | [`did`](did.qmd)                                                      | [`csdid`](csdid.qmd)       |
|                                       | Callaway and Sant'Anna (2021). Matching and reweighting non-parametric estimator for staggered treatment.                                                                                             |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| imputation / counterfactual / 2-stage | ::: small                                                                                                                                                                                             | [`fect`](fect.qmd) [`did2s`](did2s.qmd) [`didimputation`](impute.qmd) | --                         |
|                                       | Borusyak et al (2024), Gardner (2021), and Liu et al (2024). Imputation estimator using a simple fixed effects design for staggered and non-absorbing treatment.                                      |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| interactive fixed effects (ifect)     | ::: small                                                                                                                                                                                             | [`fect`](fect.qmd)                                                    | --                         |
|                                       | Xu (2017) and Liu et al (2024). Imputation estimator using estimated latent trends for staggered and non-absorbing treatment. Can be semi-robust to parallel trends violations.                       |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| matrix completion (mc)                | ::: small                                                                                                                                                                                             | [`fect`](fect.qmd)                                                    | --                         |
|                                       | Athey (2017) and Liu et al (2024). Imputation estimator using computer-science matrix completion methods for staggered and non-absorbing treatment. Can be semi-robust to parallel trends violations. |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| did multiple                          | ::: small                                                                                                                                                                                             | [`DIDmultiplegtDYN`](didmultiple.qmd)                                 | --                         |
|                                       | de Chaisemartin and D'Haultfœuille (2020, 2024). Matching and reweighting estimator that for staggered and non-absorbing treatment. Also handles continuous treatment.                                |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| panelmatch                            | ::: small                                                                                                                                                                                             | [`PanelMatch`](panelmatch.qmd)                                        | --                         |
|                                       | Imai et al (2023). Matching and reweighting estimator for staggered and non-absorbing treatment.                                                                                                      |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+
| extended twfe                         | ::: small                                                                                                                                                                                             | [`etwfe`](etwfe.qmd)                                                  | --                         |
|                                       | Wooldridge (2021, 2023). Imputation estimator using two-way mundlak regression for staggered treatment.                                                                                               |                                                                       |                            |
|                                       | :::                                                                                                                                                                                                   |                                                                       |                            |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+----------------------------+

: {tbl-colwidths="\[24,40,18,18\]"}

<br />

::: {.callout-note collapse="true" appearance="simple"}
## Additional Resources

+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
| Resource                                                                                        | Author           | Notes                                                               |
+=================================================================================================+==================+=====================================================================+
| [Yiqing Xu: modern advancements in DiD](https://yiqingxu.org/packages/fect/05-panel.html#csdid) | Yiqing Xu        | Useful overview of all modern DiD methods and R code.               |
+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
| [Asjad Naqvi: repository on DiD](https://asjadnaqvi.github.io/DiD/)                             | Asjad Naqvi      | Useful R and state code for DiD.                                    |
+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
| [User Guides for DiD](https://bcallaway11.github.io/did/articles/index.html)                    | Brantly Callaway | Useful guides and explanations of DiD with R.                       |
+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
| [Lecture: Problems with TWFE](https://psantanna.com/DiD/11_Staggered_problems.pdf)              | Pedro Sant'Anna  | Bacon decomposition and introduction to csdid.                      |
+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
| [Causal Inference: The Mixtape](https://mixtape.scunning.com/)                                  | Scott Cunningham | Textbook chapter introducing DiD.                                   |
+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
| [Chiu et al (2025)](https://yiqingxu.org/papers/english/2023_panel/CLLX.pdf)                    | Chiu et al       | Paper exploring new DiD methods and reanalysing old polisci papers. |
+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
| [Roth et al (2025)](https://www.jonathandroth.com/assets/files/DiD_Review_Paper.pdf)            | Roth et al       | An overview of new DiD methods.                                     |
+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
| [Liu et al (2025)](https://yiqingxu.org/papers/english/2022_fect/LWX2022.pdf)                   | Liu et al        | An overview of imputation DiD methods.                              |
+-------------------------------------------------------------------------------------------------+------------------+---------------------------------------------------------------------+
:::